
name: Abrir issue
description: Template ara reportar uma issue
title: "issue: <title>"
labels: [fix, triage]
body:
- type: checkboxes
  attributes:
    label: Ainda não existe uma "issue" ja aberta para esse problema ?
    description: Certifique-se que ainda não existe um problema semelhante repotado antes de abrir um novo.
    options:
      - label: Eu procurei se existe ja uma "issue" para o meu problema
        required: true

- type: textarea
  attributes:
    label: Comportamento atual
    placeholder: 'Descreva brevemente qual o problema encontrado ...'
  validations:
    required: true

- type: textarea
  attributes:
    label: Comportamento esperado
    placeholder: 'Descreva brevemente qual o comportamento esperado...'
  validations:
    required: true
    
- type: textarea
  attributes:
    label: Ambiente executado
    description: |
      Descreva como reproduzir o problema reportado...
      exemplo:
      - **OS**: Ubuntu 20.04
      - **Node**: 13.14.0
      - **npm**: 7.6.3
    value: |
        - OS:
        - Node:
        - npm:
    render: Markdown
  validations:
    required: true

- type: textarea
  attributes:
    label: Como reproduzir o probema
    description: Descreva o ambiente em que esse problema ocorreu...
    placeholder: |
      Descreva como reproduzir o problema reportado...
      1. No ambiente x ...
      2. Com a configuraçao y...
      3. execute o comando `npm run dev`
      4. Observe o comportamento errado no componete z
  validations:
    required: true