name: Playwright Tests
on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    types: [ opened, edited, synchronize ]
    branches: [ main, master, develop ]
    
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and run Docker Compose
      run: docker-compose up -d --build

    - name: Wait for the application to be ready
      run: |
        echo "Waiting for the application to start..."
        ATTEMPTS=0
        MAX_ATTEMPTS=30
        until $(curl --output /dev/null --silent --head --fail http://localhost:3000) || [ $ATTEMPTS -eq $MAX_ATTEMPTS ]; do
          printf '.'
          ATTEMPTS=$((ATTEMPTS+1))
          sleep 10
        done
        if [ $ATTEMPTS -eq $MAX_ATTEMPTS ]; then
          echo "Application failed to start within expected time."
          exit 1
        fi
      timeout-minutes: 5

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 1
    - name: Stop and clean Docker Compose
      run: docker-compose down
      if: always()